version: "3.8"

services:
  controller:
    image: ansible-ubuntu-controller
    container_name: ${COMPOSE_PROJECT_NAME}-controller
    hostname: ${COMPOSE_PROJECT_NAME}-controller
    volumes:
      - ansible_vol:/var/ansible-volume
      - "./data/controller/scripts/start-endpoint.sh:/start-endpoint.sh"
      # ansible conf
      - "./data/controller/conf/etc/ansible/ansible.cfg:/etc/ansible/ansible.cfg"
      # ansible playbooks \ inventories \ roles
      - "./data/controller/ansible/:/root/ansible/"
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  ubuntu01:
    image: ansible-ubuntu-minion
    container_name: ${COMPOSE_PROJECT_NAME}-ubuntu01
    hostname: ${COMPOSE_PROJECT_NAME}-ubuntu01
    volumes:
      - ansible_vol:/var/ansible-volume
      - "./data/ubuntu-minion/scripts/start-endpoint.sh:/start-endpoint.sh"
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - "controller"

  centos01:
    image: ansible-centos-minion
    container_name: ${COMPOSE_PROJECT_NAME}-centos01
    hostname: ${COMPOSE_PROJECT_NAME}-centos01
    volumes:
      - ansible_vol:/var/ansible-volume
      - "./data/centos-minion/scripts/start-endpoint.sh:/start-endpoint.sh"
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - "controller"

volumes:
  ansible_vol:
